### ISSUE TITLE
Issue for exception (Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException)

### ISSUE THREAD

**Issue by BMichaelJ** [BMichaelJ/Presentations#2]
**Operation Name:** HttpTriggerPoSh

**Timestamp:** 2021-06-02T22:29:26.7030000Z

**Problem Id:** Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException

**Assembly:** System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

**Exception Type:** Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException

**Method:** System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw

**Outer Exception Type:** Microsoft.Azure.WebJobs.Host.FunctionInvocationException

**Outer Exception Message:** Exception while executing function: Functions.HttpTriggerPoSh

**Outer Exception Assembly:** System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

**Outer Exception Method:** System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw

**Innermost Exception Type:** Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException

**Innermost Exception Message:** Result: Failure
Exception: The script file 'C:\home\site\wwwroot\HttpTriggerPoSh\run.ps1' has parsing errors:
Unexpected token 'in' in expression or statement.
Missing closing ')' in expression.
Missing closing '}' in statement block or type definition.
Unexpected token ')' in expression or statement.
Unexpected token '}' in expression or statement.

Stack:    at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo.GetParameters(String scriptFile, String entryPoint, ScriptBlockAst& scriptAst) in /home/vsts/work/1/s/src/FunctionInfo.cs:line 170
   at Microsoft.Azure.Functions.PowerShellWorker.AzFunctionInfo..ctor(RpcFunctionMetadata metadata) in /home/vsts/work/1/s/src/FunctionInfo.cs:line 73
   at Microsoft.Azure.Functions.PowerShellWorker.FunctionLoader.LoadFunction(FunctionLoadRequest request) in /home/vsts/work/1/s/src/FunctionLoader.cs:line 52
   at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessFunctionLoadRequest(StreamingMessage request) in /home/vsts/work/1/s/src/RequestProcessor.cs:line 222

**Country or region:** France

**State or province:** Paris

**City:** Paris

**Link:** https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22:%22317d1bcd-601f-4c84-9bed-3e0cd5a7029e%22,%22ResourceGroup%22:%22Cloud8%22,%22Name%22:%22Cloud8PoSh%22%7D/DataModel/%7B%22eventId%22:%221489fa83-c3f2-11eb-869c-2818787afd4d%22,%22timestamp%22:%222021-06-02T22:29:26.703Z%22%7D

**Comment by BMichaelJ** [comment]
Testing this out
